- 주제들/Spring IoC, DI/README.md
> 테코톡 스터디 : Spring IoC/DI 시청완료

- 주제들/Process&Thread/README.md
> chaselover

- 주제들/Context Switching/README.md
> Context Switching

- 주제들/Generics/README.md
Generics finished 21.07.08(THU)
> [Generics] update README.md

- 주제들/Cache/README.md
> Update Cache README.md

- 주제들/트랜잭션/README.md
> 트랜잭션 UPDATE

- 주제들/API vs Library vs Framework/README.md
Update API vs Library vs Framework
> Update API vs Library vs Framework

- 주제들/Web Server vs WAS/README.md
> Update Web Server vs WAS

- 주제들/Web Server vs WAS/README.md
> 웹서버 vs WAS : 시청완료

- 주제들/Apache MPM vs NGINX vs Node.js/README.md
Apache MPM vs NGINX vs Node.js
> Update Apache MPM vs NGINX vs Node.js

- 주제들/Forward Proxy vs Reverse Proxy, Load Balancer/README.md
Forward Proxy vs Reverse Proxy, Load Balancer
> Forward Proxy vs Reverse Proxy, Load Balancer

- 주제들/트랜잭션/README.md
> 테코톡 스터디 : 트랜잭션 시청완료

- 주제들/OSI 7 Layer/README.md
> UPDATE OSI 7 Layer

- 주제들/HTTP1.1, HTTP2, QUIC/README.md
> UPDATE HTTP1.1 HTTP2.0 QUIC

- 주제들/교착상태/README.md
> 테코톡 스터디 : 교착상태

- 주제들/Block vs Non-Block & Sync vs Async/README.md
UPDATE Blocking vs NonBlocking and Sync vs Async
> UPDATE Blocking vs NonBlocking and Sync vs Async

- 주제들/JVM Garbage Collector/README.md
> 테코톡 스터디 : JVM Garbage Collector 시청완료

- 주제들/AOP/README.md
AOP에 대해서 정리했습니다.[링크](https://github.com/kwj1270/TIL_Seminar/blob/master/AOP.md)
테코톡 AOP 영상 외에도 제가 직접 공부한 내용들(구글링 + 강의 + 책)에 대해서 정리했으니
한 번 참고하시면 좋을 것 같아요 :)
> feat(kwj1270):0726 AOP 시청

- 주제들/DNS/README.md
> Docs tech-talk about DNS

- 주제들/Realtime Web/README.md
> Feat Realtime Web

- 주제들/프론트엔드에서의 테스트 종류/README.md
> Mkdir 프론트엔드에서의 테스트

- README.md
- 주제들/프론트엔드에서의 테스트 종류/README.md
> docs README.md

- 주제들/Process&Thread/README.md
- 주제들/리눅스 메모리 관리/README.md
Process&Thread 의 README.md 에 aeroej 추가했습니다.
> Process&Thread 시청완료, 리눅스 메모리 관리 추가

- README.md
Signed-off-by: aeroej <asd0755@naver.com>
Techo-Talk-Study/README.md 의 
영상 목록에 **리눅스 메모리 관리** 추가
> 메인 README.md 업데이트

- 주제들/Redis/README.md
> Update: Update Redis README.md

- 주제들/JVM Garbage Collector/README.md
> 테코톡 스터디 : JVM Garbage Collector 시청완료 
